### ISSUE TITLE
Qwen1.5-7B-Chat

### ISSUE THREAD

**Issue by ChuanhongLi** [thunlp/InfLLM#20]
Qwen系列的模型，有对应的测试结果吗？ 

PS：默认的 yaml 配置 跑 qasper 数据集会直接爆显存（NVIDIA A100-SXM4-80GB）

```
model:
  type: inf-llm
  path: /data/model/open_source_data/Qwen/Qwen1.5-7B-Chat
  block_size: 128
  n_init: 128
  n_local: 4096
  topk: 16
  repr_topk: 4
  max_cached_block: 32
  exc_block_size: 512
  score_decay: 0.1
  fattn: true
  base: 1000000
  distance_scale: 1.0

max_len: 2147483647
chunk_size: 4096 (8192 也是爆显存)
conv_type: qwen
```

**Comment by yinochaos** [comment]
同样的问题，太容易爆显存了，修改device_map，使用多卡，也会报错：
`  File "/maindata/data/user/elvin.e/git/InfLLM/inf_llm/attention/inf_llm.py", line 58, in forward
    o = past_key_value.append(
  File "/maindata/data/user/elvin.e/git/InfLLM/inf_llm/attention/context_manager.py", line 685, in append
    global_q = self.position_embedding.apply_rotary_pos_emb_one_angle(
  File "/maindata/data/user/elvin.e/git/InfLLM/inf_llm/attention/rope.py", line 104, in apply_rotary_pos_emb_one_angle
    return ((x.float() * cos) + (self.rotate_half(x).float() * sin)).to(dtype)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!`

**Comment by guyan364** [comment]
> Qwen系列的模型，有对应的测试结果吗？
> 
> PS：默认的 yaml 配置 跑 qasper 数据集会直接爆显

目前没有结果，之后我们会更新。

我使用这份 config，可以在 A40 上跑 qasper。可以提供更多的错误信息吗。

**Comment by guyan364** [comment]
> 同样的问题，太容易爆显存了，修改device_map，使用多卡，也会报错：
> 
> ```
> File "/maindata/data/user/elvin.e/git/InfLLM/inf_llm/attention/inf_llm.py", line 58, in forward
>     o = past_key_value.append(
>   File "/maindata/data/user/elvin.e/git/InfLLM/inf_llm/attention/context_manager.py", line 685, in append
>     global_q = self.position_embedding.apply_rotary_pos_emb_one_angle(
>   File "/maindata/data/user/elvin.e/git/InfLLM/inf_llm/attention/rope.py", line 104, in apply_rotary_pos_emb_one_angle
>     return ((x.float() * cos) + (self.rotate_half(x).float() * sin)).to(dtype)
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
> ```

你好，目前不支持多卡推理。如果遇到爆显存的问题，可以尝试修改 config 中的 chunk_size 到 512.

**Comment by ChuanhongLi** [comment]
> > Qwen系列的模型，有对应的测试结果吗？
> > PS：默认的 yaml 配置 跑 qasper 数据集会直接爆显
> 
> 目前没有结果，之后我们会更新。
> 
> 我使用这份 config，可以在 A40 上跑 qasper。可以提供更多的错误信息吗。

```
model:
  type: inf-llm
  path: /data/model/open_source_data/Qwen/Qwen1.5-7B-Chat
  block_size: 128
  n_init: 128
  n_local: 4096
  topk: 8
  repr_topk: 4
  max_cached_block: 32
  exc_block_size: 512
  score_decay: 0.1
  fattn: true
  base: 1000000
  distance_scale: 1.0

max_len: 2147483647
chunk_size: 4096
conv_type: qwen
```
目前修改了topk 的值正在测试，稍后我复现下上面的问题；另外使用 origin，修改 yaml 文件如下：
```
model:
  type: origin
  path: data/model/open_source_data/Qwen/Qwen1.5-7B-Chat
  fattn: true
  base: 1000000
  distance_scale: 1.0

max_len: 32768
chunk_size: 4096
conv_type: qwen
```
会报错 TypeError: flash_attn_func() missing 1 required positional argument: 'max_s'， 是flash attention 的版本不匹配吗？
